export interface CubbonTreeSpecies {
  serialNo: number;
  scientificName: string;
  commonName: string;
  kannadaName?: string;
  family: string;
  canopyType: 'Broadleaf Evergreen' | 'Deciduous' | 'Semi-evergreen' | 'Palm / Conifer' | 'Flowering Canopy';
  typicalHeightM: number;
  typicalCanopySpreadM: number;
  ecologicalRole: 'Keystone Food Source' | 'Mother Tree / Continuous Canopy' | 'Nectar / Pollinator Anchor' | 'Medicinal & Microclimate' | 'Soil & Nitrogen Fixer';
  faunaAffinity: string[];
  nativeStatus: 'Native' | 'Introduced / Naturalized';
  conservationNote?: string;
}

export const CUBBON_PARK_SPECIES: CubbonTreeSpecies[] = [
  {
    serialNo: 1,
    scientificName: "Acacia auriculiformis A. Cunn. ex Benth.",
    commonName: "Earleaf Acacia / Australian Wattle",
    kannadaName: "Aakashamallige / Holay",
    family: "Fabaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 18,
    typicalCanopySpreadM: 12,
    ecologicalRole: "Soil & Nitrogen Fixer",
    faunaAffinity: ["Honeybees", "Bark Foraging Birds", "Tree Pipits"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 2,
    scientificName: "Acacia ferruginea DC.",
    commonName: "Rusty Acacia",
    kannadaName: "Banni Mara",
    family: "Fabaceae",
    canopyType: "Deciduous",
    typicalHeightM: 14,
    typicalCanopySpreadM: 11,
    ecologicalRole: "Soil & Nitrogen Fixer",
    faunaAffinity: ["Indian Flying Fox", "Sunbirds", "Wild Pollinators"],
    nativeStatus: "Native"
  },
  {
    serialNo: 3,
    scientificName: "Adenanthera pavonina L.",
    commonName: "Red Bead Tree / Coral Wood",
    kannadaName: "Manjadi Mara",
    family: "Fabaceae",
    canopyType: "Deciduous",
    typicalHeightM: 16,
    typicalCanopySpreadM: 14,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Parakeets", "Grey Slender Loris", "Tree Frogs"],
    nativeStatus: "Native"
  },
  {
    serialNo: 4,
    scientificName: "Aegle marmelos (L.) Corrêa",
    commonName: "Bael / Sacred Bilva",
    kannadaName: "Bilva Patre",
    family: "Rutaceae",
    canopyType: "Deciduous",
    typicalHeightM: 12,
    typicalCanopySpreadM: 9,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Lime Butterflies", "Langurs", "Palm Civets"],
    nativeStatus: "Native"
  },
  {
    serialNo: 5,
    scientificName: "Agathis robusta (C.Moore ex F.Muell.) F.M.Bailey",
    commonName: "Queensland Kauri Pine",
    family: "Araucariaceae",
    canopyType: "Palm / Conifer",
    typicalHeightM: 32,
    typicalCanopySpreadM: 16,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Raptors", "Spotted Owlets", "Indian Giant Squirrels"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 6,
    scientificName: "Aglaia elaeagnoidea (A. Juss.) Benth.",
    commonName: "Coastal Aglaia",
    family: "Meliaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 15,
    typicalCanopySpreadM: 10,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Bulbuls", "Barbets", "Frugivorous Bats"],
    nativeStatus: "Native"
  },
  {
    serialNo: 7,
    scientificName: "Ailanthus triphysa (Denst.) Alston",
    commonName: "White Dammar / Halmaddi",
    kannadaName: "Halmaddi",
    family: "Simaroubaceae",
    canopyType: "Deciduous",
    typicalHeightM: 24,
    typicalCanopySpreadM: 15,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Weaver Ants", "Sunbirds", "Giant Wood Spiders"],
    nativeStatus: "Native"
  },
  {
    serialNo: 8,
    scientificName: "Alangium salviifolium (L.f.) Wangerin.",
    commonName: "Sage Leaved Alangium",
    kannadaName: "Ankole",
    family: "Cornaceae",
    canopyType: "Deciduous",
    typicalHeightM: 10,
    typicalCanopySpreadM: 8,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Honeybees", "Bark Creepers", "Hornbills"],
    nativeStatus: "Native"
  },
  {
    serialNo: 9,
    scientificName: "Albizia julibrissin Durazz.",
    commonName: "Persian Silk Tree",
    family: "Fabaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 12,
    typicalCanopySpreadM: 14,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Swallowtail Butterflies", "Hawkmoths", "Sunbirds"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 10,
    scientificName: "Albizia lebbeck (L.) Benth.",
    commonName: "Siris / Woman's Tongue Tree",
    kannadaName: "Bage Mara",
    family: "Fabaceae",
    canopyType: "Deciduous",
    typicalHeightM: 20,
    typicalCanopySpreadM: 18,
    ecologicalRole: "Soil & Nitrogen Fixer",
    faunaAffinity: ["Grey Slender Loris", "Tree Frogs", "Parakeets"],
    nativeStatus: "Native"
  },
  {
    serialNo: 11,
    scientificName: "Albizia odoratissima (L.f.) Benth.",
    commonName: "Fragrant Siris",
    kannadaName: "Bilwara",
    family: "Fabaceae",
    canopyType: "Deciduous",
    typicalHeightM: 22,
    typicalCanopySpreadM: 17,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Barbets", "Arboreal Geckoes", "Carpenter Bees"],
    nativeStatus: "Native"
  },
  {
    serialNo: 12,
    scientificName: "Alstonia macrophylla Wall. ex G.Don",
    commonName: "Batino / Large-leaf Alstonia",
    family: "Apocynaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 25,
    typicalCanopySpreadM: 15,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Fruit Bats", "Tree Squirrels", "Orioles"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 13,
    scientificName: "Alstonia scholaris (L.) R. Br.",
    commonName: "Devil's Tree / Saptaparni",
    kannadaName: "Maddale",
    family: "Apocynaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 26,
    typicalCanopySpreadM: 18,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Moths", "Nocturnal Pollinators", "Grey Slender Loris"],
    nativeStatus: "Native"
  },
  {
    serialNo: 14,
    scientificName: "Annona muricata L.",
    commonName: "Soursop / Graviola",
    family: "Annonaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 9,
    typicalCanopySpreadM: 7,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Frugivorous Bats", "Palm Civets", "Barbets"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 15,
    scientificName: "Aphanamixis polystachya (Wall.) R. Parker",
    commonName: "Pithraj Tree",
    kannadaName: "Rohitaka",
    family: "Meliaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 18,
    typicalCanopySpreadM: 13,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Bulbuls", "White-eyes", "Bark Beetles"],
    nativeStatus: "Native"
  },
  {
    serialNo: 16,
    scientificName: "Aquilaria malaccensis Lam.",
    commonName: "Agarwood / Eaglewood",
    family: "Thymelaeaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 20,
    typicalCanopySpreadM: 12,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Fungus Weevils", "Canopy Ants", "Orioles"],
    nativeStatus: "Native",
    conservationNote: "Critically endangered keystone"
  },
  {
    serialNo: 17,
    scientificName: "Araucaria columnaris (G.Forst.) Hook.",
    commonName: "Cook Pine / New Caledonia Pine",
    family: "Araucariaceae",
    canopyType: "Palm / Conifer",
    typicalHeightM: 35,
    typicalCanopySpreadM: 9,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Black Kites", "Spotted Owlets", "Brahminy Kites"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 18,
    scientificName: "Araucaria cunninghamii Mudie.",
    commonName: "Hoop Pine",
    family: "Araucariaceae",
    canopyType: "Palm / Conifer",
    typicalHeightM: 32,
    typicalCanopySpreadM: 11,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Raptors", "Arboreal Bats", "Indian Giant Squirrels"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 19,
    scientificName: "Artabotrys hexapetalus (L.f.) Bhandari",
    commonName: "Climbing Ylang Ylang / Manoranjitham",
    kannadaName: "Manoranjani",
    family: "Annonaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 8,
    typicalCanopySpreadM: 8,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Nocturnal Moths", "Honeybees", "Sunbirds"],
    nativeStatus: "Native"
  },
  {
    serialNo: 20,
    scientificName: "Artocarpus heterophyllus Lam",
    commonName: "Jackfruit Tree",
    kannadaName: "Halasina Mara",
    family: "Moraceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 22,
    typicalCanopySpreadM: 19,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Indian Giant Squirrel", "Grey Slender Loris", "Civets", "Fruit Bats"],
    nativeStatus: "Native"
  },
  {
    serialNo: 21,
    scientificName: "Artocarpus lacucha Buch.-Ham",
    commonName: "Monkey Jack",
    kannadaName: "Vate Huli",
    family: "Moraceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 20,
    typicalCanopySpreadM: 16,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Bonnet Macaques", "Grey Slender Loris", "Flying Foxes"],
    nativeStatus: "Native"
  },
  {
    serialNo: 22,
    scientificName: "Averrhoa carambola L.",
    commonName: "Star Fruit / Carambola",
    kannadaName: "Kaparakshi",
    family: "Oxalidaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 9,
    typicalCanopySpreadM: 8,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Palm Civets", "Squirrels", "Bulbuls"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 23,
    scientificName: "Azadirachta indica A. Juss.",
    commonName: "Neem / Margosa Tree",
    kannadaName: "Bevu Mara",
    family: "Meliaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 20,
    typicalCanopySpreadM: 18,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Asian Koel", "Tree Frogs", "Beneficial Insects", "Grey Slender Loris"],
    nativeStatus: "Native"
  },
  {
    serialNo: 24,
    scientificName: "Barringtonia acutangula (L.) Gaertn.",
    commonName: "Freshwater Mangrove / Indian Oak",
    kannadaName: "Hole Kauva",
    family: "Lecythidaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 13,
    typicalCanopySpreadM: 11,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Kingfishers", "Pond Herons", "Drongos"],
    nativeStatus: "Native"
  },
  {
    serialNo: 25,
    scientificName: "Barringtonia asiatica (L.) Kurz.",
    commonName: "Sea Poison Tree / Fish Poison Tree",
    family: "Lecythidaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 18,
    typicalCanopySpreadM: 16,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Fruit Bats", "Moths", "Nightjars"],
    nativeStatus: "Native"
  },
  {
    serialNo: 26,
    scientificName: "Bauhinia purpurea L.",
    commonName: "Purple Orchid Tree",
    kannadaName: "Kanchavala",
    family: "Fabaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 12,
    typicalCanopySpreadM: 12,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Purple Sunbird", "Carpenter Bees", "Silverline Butterflies"],
    nativeStatus: "Native"
  },
  {
    serialNo: 27,
    scientificName: "Bauhinia tomentosa L.",
    commonName: "Yellow Bell Orchid Tree",
    family: "Fabaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 8,
    typicalCanopySpreadM: 7,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Sunbirds", "Bees", "Small Foraging Birds"],
    nativeStatus: "Native"
  },
  {
    serialNo: 28,
    scientificName: "Beaucarnea recurvata Lem.",
    commonName: "Ponytail Palm / Elephant Foot Tree",
    family: "Asparagaceae",
    canopyType: "Palm / Conifer",
    typicalHeightM: 7,
    typicalCanopySpreadM: 5,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Geckoes", "Spiders", "Tailorbirds"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 29,
    scientificName: "Bixa orellana L",
    commonName: "Annatto / Lipstick Tree",
    family: "Bixaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 8,
    typicalCanopySpreadM: 6,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Stingless Bees", "Sunbirds", "Flies"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 30,
    scientificName: "Bombax ceiba L.",
    commonName: "Red Silk Cotton / Semal",
    kannadaName: "Booruga Mara",
    family: "Malvaceae",
    canopyType: "Deciduous",
    typicalHeightM: 30,
    typicalCanopySpreadM: 24,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Grey Slender Loris", "Myna", "Rosy Starling", "Giant Squirrel", "Langurs"],
    nativeStatus: "Native"
  },
  {
    serialNo: 31,
    scientificName: "Brownea grandiceps Jacq",
    commonName: "Rose of Venezuela",
    family: "Fabaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 11,
    typicalCanopySpreadM: 10,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Hummingbird Moths", "Sunbirds", "Honeybees"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 32,
    scientificName: "Butea monosperma (Lam.) Kuntze",
    commonName: "Flame of the Forest / Palash",
    kannadaName: "Muthuga",
    family: "Fabaceae",
    canopyType: "Deciduous",
    typicalHeightM: 15,
    typicalCanopySpreadM: 14,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Sunbirds", "Parakeets", "Honeybees", "Common Palm Civet"],
    nativeStatus: "Native"
  },
  {
    serialNo: 33,
    scientificName: "Calliandra haematocephala Hassk",
    commonName: "Red Powder Puff",
    family: "Fabaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 6,
    typicalCanopySpreadM: 6,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Butterflies", "Sunbirds", "Bees"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 34,
    scientificName: "Melaleuca citrina (Curtis) Dum.Cours.",
    commonName: "Crimson Bottlebrush",
    family: "Myrtaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 8,
    typicalCanopySpreadM: 7,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Sunbirds", "Lorikeets", "Honeybees"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 35,
    scientificName: "Callistemon viminalis (Sol. ex Gaertn.) Byrnes",
    commonName: "Weeping Bottlebrush",
    family: "Myrtaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 10,
    typicalCanopySpreadM: 8,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["White-eyes", "Sunbirds", "Leaf Miners"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 36,
    scientificName: "Calophyllum inophyllum L.",
    commonName: "Alexandrian Laurel / Sultan Champa",
    kannadaName: "Honne Mara",
    family: "Calophyllaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 20,
    typicalCanopySpreadM: 17,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Fruit Bats", "Owls", "Grey Slender Loris"],
    nativeStatus: "Native"
  },
  {
    serialNo: 37,
    scientificName: "Careya arborea Roxb.",
    commonName: "Wild Guava / Kumbi",
    kannadaName: "Kaval Mara",
    family: "Lecythidaceae",
    canopyType: "Deciduous",
    typicalHeightM: 16,
    typicalCanopySpreadM: 13,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Deer", "Wild Boar", "Frugivorous Bats"],
    nativeStatus: "Native"
  },
  {
    serialNo: 38,
    scientificName: "Caryota urens L",
    commonName: "Fishtail Palm / Jaggery Palm",
    kannadaName: "Baine Mara",
    family: "Arecaceae",
    canopyType: "Palm / Conifer",
    typicalHeightM: 18,
    typicalCanopySpreadM: 8,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Grey Slender Loris", "Civets", "Fruit Bats"],
    nativeStatus: "Native"
  },
  {
    serialNo: 39,
    scientificName: "Cassia fistula L.",
    commonName: "Golden Shower / Amaltas",
    kannadaName: "Kakke Mara",
    family: "Fabaceae",
    canopyType: "Deciduous",
    typicalHeightM: 14,
    typicalCanopySpreadM: 12,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Emigrant Butterflies", "Carpenter Bees", "Golden Orioles"],
    nativeStatus: "Native"
  },
  {
    serialNo: 40,
    scientificName: "Cassia grandis L.f.",
    commonName: "Pink Shower / Horse Cassia",
    family: "Fabaceae",
    canopyType: "Deciduous",
    typicalHeightM: 18,
    typicalCanopySpreadM: 15,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Sunbirds", "Wild Bees", "Parakeets"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 41,
    scientificName: "Cassia javanica L.",
    commonName: "Java Cassia / Apple Blossom Tree",
    family: "Fabaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 16,
    typicalCanopySpreadM: 14,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Honeybees", "Tailorbirds", "Barbets"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 42,
    scientificName: "Cassia roxburghii DC.",
    commonName: "Red Cassia / Ceylon Senna",
    family: "Fabaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 15,
    typicalCanopySpreadM: 13,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Butterflies", "Sunbirds", "Flowerpeckers"],
    nativeStatus: "Native"
  },
  {
    serialNo: 43,
    scientificName: "Cassine paniculata (Wight & Arn.) T.P. Ramamoorthy",
    commonName: "Paniculate Cassine",
    family: "Celastraceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 14,
    typicalCanopySpreadM: 11,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Small Passerine Birds", "Tree Mantises"],
    nativeStatus: "Native"
  },
  {
    serialNo: 44,
    scientificName: "Castanospermum australe A.Cunn. ex Mudie",
    commonName: "Moreton Bay Chestnut / Blackbean",
    family: "Fabaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 22,
    typicalCanopySpreadM: 16,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Sunbirds", "Flying Foxes", "Giant Squirrels"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 45,
    scientificName: "Casuarina equisetifolia L.",
    commonName: "Whistling Pine / Beefwood",
    kannadaName: "Sarve Mara",
    family: "Casuarinaceae",
    canopyType: "Palm / Conifer",
    typicalHeightM: 25,
    typicalCanopySpreadM: 10,
    ecologicalRole: "Soil & Nitrogen Fixer",
    faunaAffinity: ["Kites", "Munias", "Green Bee-eaters"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 46,
    scientificName: "Ceiba pentandra (L.) Gaertn.",
    commonName: "Kapok Tree / White Silk Cotton",
    kannadaName: "Bili Booruga",
    family: "Malvaceae",
    canopyType: "Deciduous",
    typicalHeightM: 38,
    typicalCanopySpreadM: 28,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Fruit Bats", "Grey Slender Loris", "Owls", "Indian Giant Squirrel"],
    nativeStatus: "Native"
  },
  {
    serialNo: 47,
    scientificName: "Ceiba speciosa (A.St.-Hil., A.Juss. & Cambess.) Ravenna",
    commonName: "Floss Silk Tree",
    family: "Malvaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 22,
    typicalCanopySpreadM: 18,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Hummingbird Hawkmoths", "Sunbirds", "Fruit Bats"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 48,
    scientificName: "Centrolobium tomentosum Guill. ex Benth",
    commonName: "Yellow Arariba",
    family: "Fabaceae",
    canopyType: "Deciduous",
    typicalHeightM: 24,
    typicalCanopySpreadM: 16,
    ecologicalRole: "Soil & Nitrogen Fixer",
    faunaAffinity: ["Woodpeckers", "Barbets", "Arboreal Termites"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 49,
    scientificName: "Cerbera odollam Gaertn",
    commonName: "Suicide Tree / Sea Mango",
    kannadaName: "Odalanga",
    family: "Apocynaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 12,
    typicalCanopySpreadM: 9,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Sphinx Moths", "Bark Lizards"],
    nativeStatus: "Native"
  },
  {
    serialNo: 50,
    scientificName: "Chukrasia tabularis A. Juss.",
    commonName: "Indian Mahogany / Chittagong Wood",
    kannadaName: "Kalgarige",
    family: "Meliaceae",
    canopyType: "Deciduous",
    typicalHeightM: 26,
    typicalCanopySpreadM: 19,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Grey Slender Loris", "Woodpeckers", "Hornbills"],
    nativeStatus: "Native"
  },
  {
    serialNo: 51,
    scientificName: "Cinnamomum verum J.Presl.",
    commonName: "True Cinnamon",
    kannadaName: "Lavanga Patre",
    family: "Lauraceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 14,
    typicalCanopySpreadM: 10,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Common Myna", "Barbets", "Butterflies"],
    nativeStatus: "Native"
  },
  {
    serialNo: 52,
    scientificName: "Citharexylum spinosum L.",
    commonName: "Fiddlewood",
    family: "Verbenaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 12,
    typicalCanopySpreadM: 10,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Sunbirds", "Honeybees", "White-eyes"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 53,
    scientificName: "Citrus × limon (L.) Osbeck",
    commonName: "Lemon Tree",
    kannadaName: "Nimbe Mara",
    family: "Rutaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 6,
    typicalCanopySpreadM: 5,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Lime Butterfly Caterpillars", "Honeybees"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 54,
    scientificName: "Clitoria arborea Benth.",
    commonName: "Tree Butterfly Pea",
    family: "Fabaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 10,
    typicalCanopySpreadM: 8,
    ecologicalRole: "Soil & Nitrogen Fixer",
    faunaAffinity: ["Carpenter Bees", "Skipper Butterflies"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 55,
    scientificName: "Cocos nucifera L.",
    commonName: "Coconut Palm",
    kannadaName: "Tengina Mara",
    family: "Arecaceae",
    canopyType: "Palm / Conifer",
    typicalHeightM: 22,
    typicalCanopySpreadM: 7,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Palm Civets", "Three-striped Palm Squirrel", "Parakeets"],
    nativeStatus: "Native"
  },
  {
    serialNo: 56,
    scientificName: "Colvillea racemosa Boj.",
    commonName: "Colville's Glory",
    family: "Fabaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 16,
    typicalCanopySpreadM: 14,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Sunbirds", "Honeybees", "Flowerpeckers"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 57,
    scientificName: "Cordia dichotoma G.Forst",
    commonName: "Fragrant Manjack / Bird Lime Tree",
    kannadaName: "Chikke Mara",
    family: "Boraginaceae",
    canopyType: "Deciduous",
    typicalHeightM: 14,
    typicalCanopySpreadM: 12,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Koel", "Grey Hornbill", "Bulbuls"],
    nativeStatus: "Native"
  },
  {
    serialNo: 58,
    scientificName: "Cordia myxa L.",
    commonName: "Assyrian Plum",
    family: "Boraginaceae",
    canopyType: "Deciduous",
    typicalHeightM: 13,
    typicalCanopySpreadM: 11,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Fruit Doves", "Green Pigeons", "Palm Civets"],
    nativeStatus: "Native"
  },
  {
    serialNo: 59,
    scientificName: "Cordia sebestena L.",
    commonName: "Geiger Tree / Scarlet Cordia",
    family: "Boraginaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 9,
    typicalCanopySpreadM: 8,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Purple-rumped Sunbird", "Stingless Bees"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 60,
    scientificName: "Couroupita guianensis Abul.",
    commonName: "Cannonball Tree / Nagalingam",
    kannadaName: "Lingada Mara",
    family: "Lecythidaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 26,
    typicalCanopySpreadM: 18,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Carpenter Bees", "Bats", "Tree Squirrels"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 61,
    scientificName: "Crescentia cujete L.",
    commonName: "Calabash Tree",
    family: "Bignoniaceae",
    canopyType: "Deciduous",
    typicalHeightM: 10,
    typicalCanopySpreadM: 9,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Fruit Bats", "Tree Frogs", "Epiphytes"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 62,
    scientificName: "Cupressus funebris Endl.",
    commonName: "Mourning Cypress / Weeping Cypress",
    family: "Cupressaceae",
    canopyType: "Palm / Conifer",
    typicalHeightM: 24,
    typicalCanopySpreadM: 10,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Spotted Owlets", "Kites", "Canopy Spiders"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 63,
    scientificName: "Cupressus sempervirens L.",
    commonName: "Mediterranean Cypress",
    family: "Cupressaceae",
    canopyType: "Palm / Conifer",
    typicalHeightM: 25,
    typicalCanopySpreadM: 6,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Birds of Prey", "Tree Shrews"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 64,
    scientificName: "Cycas circinalis L.",
    commonName: "Queen Sago / Forest Cycad",
    kannadaName: "Kaadu Eechalu",
    family: "Cycadaceae",
    canopyType: "Palm / Conifer",
    typicalHeightM: 6,
    typicalCanopySpreadM: 5,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Pollinating Weevils", "Bark Geckos"],
    nativeStatus: "Native",
    conservationNote: "Living ancient gymnosperm fossil"
  },
  {
    serialNo: 65,
    scientificName: "Dalbergia latifolia Roxb.",
    commonName: "Indian Rosewood / Sheesham",
    kannadaName: "Beete Mara",
    family: "Fabaceae",
    canopyType: "Deciduous",
    typicalHeightM: 28,
    typicalCanopySpreadM: 20,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Grey Slender Loris", "Woodpeckers", "Giant Honeybees"],
    nativeStatus: "Native",
    conservationNote: "Vulnerable heritage hardwood"
  },
  {
    serialNo: 66,
    scientificName: "Dalbergia melanoxylon",
    commonName: "African Blackwood",
    family: "Fabaceae",
    canopyType: "Deciduous",
    typicalHeightM: 12,
    typicalCanopySpreadM: 9,
    ecologicalRole: "Soil & Nitrogen Fixer",
    faunaAffinity: ["Wood Boring Beetles", "Arboreal Ants"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 67,
    scientificName: "Dalbergia sissoo Roxb. ex DC.",
    commonName: "North Indian Rosewood / Shisham",
    kannadaName: "Biridi",
    family: "Fabaceae",
    canopyType: "Deciduous",
    typicalHeightM: 22,
    typicalCanopySpreadM: 16,
    ecologicalRole: "Soil & Nitrogen Fixer",
    faunaAffinity: ["Grey Slender Loris", "Barbeting Birds", "Tree Frogs"],
    nativeStatus: "Native"
  },
  {
    serialNo: 68,
    scientificName: "Delonix regia (Bojer ex Hooke.) Raf",
    commonName: "Gulmohar / Royal Poinciana",
    kannadaName: "Kattikayi",
    family: "Fabaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 17,
    typicalCanopySpreadM: 22,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Purple Sunbird", "Honeybees", "Three-striped Palm Squirrel", "Bulbuls"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 69,
    scientificName: "Dimocarpus longan Lour.",
    commonName: "Longan / Dragon's Eye",
    family: "Sapindaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 15,
    typicalCanopySpreadM: 13,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Fruit Bats", "Civets", "Indian Giant Squirrel"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 70,
    scientificName: "Diospyros discolor A. DC.",
    commonName: "Velvet Apple / Mabolo",
    family: "Ebenaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 18,
    typicalCanopySpreadM: 14,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Palm Civets", "Flying Foxes", "Bulbuls"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 71,
    scientificName: "Diospyros malabarica (Desr.) Kostel.",
    commonName: "Malabar Ebony / Gaub Tree",
    kannadaName: "Holitupare",
    family: "Ebenaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 20,
    typicalCanopySpreadM: 15,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Grey Slender Loris", "Hornbills", "Arboreal Geckos"],
    nativeStatus: "Native"
  },
  {
    serialNo: 72,
    scientificName: "Duabanga grandiflora (Roxb. ex DC.) Walpers",
    commonName: "Lampati",
    family: "Lythraceae",
    canopyType: "Deciduous",
    typicalHeightM: 28,
    typicalCanopySpreadM: 20,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Nocturnal Bats", "Owls", "Drongos"],
    nativeStatus: "Native"
  },
  {
    serialNo: 73,
    scientificName: "Elaeis guineensis Jacq.",
    commonName: "African Oil Palm",
    family: "Arecaceae",
    canopyType: "Palm / Conifer",
    typicalHeightM: 16,
    typicalCanopySpreadM: 8,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Palm Squirrels", "Crows", "Weaver Ants"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 74,
    scientificName: "Elaeocarpus angustifolius Blume.",
    commonName: "Rudraksha Tree / Blue Marble Tree",
    kannadaName: "Rudrakshi",
    family: "Elaeocarpaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 22,
    typicalCanopySpreadM: 15,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Hornbills", "Fruit Pigeons", "Grey Slender Loris"],
    nativeStatus: "Native"
  },
  {
    serialNo: 75,
    scientificName: "Enterolobium cyclocarpum (Jacq.) Griseb.",
    commonName: "Elephant Ear Tree / Guanacaste",
    family: "Fabaceae",
    canopyType: "Deciduous",
    typicalHeightM: 30,
    typicalCanopySpreadM: 32,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Grey Slender Loris", "Spotted Owlets", "Giant Squirrels", "Fruit Bats"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 76,
    scientificName: "Eucalyptus globulus Labill.",
    commonName: "Tasmanian Blue Gum",
    kannadaName: "Neelagiri",
    family: "Myrtaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 34,
    typicalCanopySpreadM: 14,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Kites", "Mynas", "Bees"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 77,
    scientificName: "Ficus amplissima Smith",
    commonName: "Bat Fig / Indian Fig",
    kannadaName: "Bili Basari",
    family: "Moraceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 24,
    typicalCanopySpreadM: 26,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Grey Slender Loris", "Fruit Bats", "Asian Koel", "Hornbills", "Barbets"],
    nativeStatus: "Native"
  },
  {
    serialNo: 78,
    scientificName: "Ficus benghalensis L.",
    commonName: "Banyan Tree / Sacred Banyan",
    kannadaName: "Aalada Mara",
    family: "Moraceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 28,
    typicalCanopySpreadM: 40,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Grey Slender Loris", "Indian Giant Squirrel", "Spotted Owlets", "Civets", "Hornbills", "Over 40 Bird Species"],
    nativeStatus: "Native",
    conservationNote: "Supreme Cubbon Park keystone anchor"
  },
  {
    serialNo: 79,
    scientificName: "Ficus benjamina L.",
    commonName: "Weeping Fig / Benjamin Tree",
    kannadaName: "Kallu Goli",
    family: "Moraceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 20,
    typicalCanopySpreadM: 22,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Fig Wasps", "Pigeons", "Lorises", "Bulbuls"],
    nativeStatus: "Native"
  },
  {
    serialNo: 80,
    scientificName: "Ficus drupacea Thunb.",
    commonName: "Brown Woolly Fig / Mysore Fig",
    kannadaName: "Goni Mara",
    family: "Moraceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 26,
    typicalCanopySpreadM: 28,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Grey Slender Loris", "Giant Squirrel", "Barbets"],
    nativeStatus: "Native"
  },
  {
    serialNo: 81,
    scientificName: "Ficus elastica Roxb. ex Hornem.",
    commonName: "Indian Rubber Fig",
    family: "Moraceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 25,
    typicalCanopySpreadM: 24,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Tree Frogs", "Arboreal Bats", "Lorises"],
    nativeStatus: "Native"
  },
  {
    serialNo: 82,
    scientificName: "Ficus hispida L.f.",
    commonName: "Hairy Fig / Devil Fig",
    kannadaName: "Kadu Atti",
    family: "Moraceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 10,
    typicalCanopySpreadM: 9,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Bulbuls", "Short-nosed Fruit Bats", "Wasps"],
    nativeStatus: "Native"
  },
  {
    serialNo: 83,
    scientificName: "Ficus microcarpa L.f",
    commonName: "Chinese Banyan / Curtain Fig",
    kannadaName: "Itthi Mara",
    family: "Moraceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 22,
    typicalCanopySpreadM: 25,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Grey Slender Loris", "Koels", "Owlets", "Fig Wasps"],
    nativeStatus: "Native"
  },
  {
    serialNo: 84,
    scientificName: "Ficus neriifolia Sm.",
    commonName: "Willow Leaf Fig",
    family: "Moraceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 16,
    typicalCanopySpreadM: 14,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Barbets", "Leaf Warblers", "Tree Squirrels"],
    nativeStatus: "Native"
  },
  {
    serialNo: 85,
    scientificName: "Ficus racemosa L.",
    commonName: "Cluster Fig / Gular",
    kannadaName: "Atti Mara",
    family: "Moraceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 22,
    typicalCanopySpreadM: 22,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Grey Slender Loris", "Civets", "Bonnet Macaques", "Over 30 bird species"],
    nativeStatus: "Native"
  },
  {
    serialNo: 86,
    scientificName: "Ficus religiosa L.",
    commonName: "Sacred Fig / Peepal Tree",
    kannadaName: "Arali Mara",
    family: "Moraceae",
    canopyType: "Deciduous",
    typicalHeightM: 30,
    typicalCanopySpreadM: 32,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Grey Slender Loris", "Giant Flying Fox", "Koels", "Barbets", "Parakeets"],
    nativeStatus: "Native"
  },
  {
    serialNo: 87,
    scientificName: "Ficus virens Aiton.",
    commonName: "White Fig / Pilkhan",
    kannadaName: "Basari Mara",
    family: "Moraceae",
    canopyType: "Deciduous",
    typicalHeightM: 26,
    typicalCanopySpreadM: 28,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Hornbills", "Barbets", "Grey Slender Loris", "Giant Squirrel"],
    nativeStatus: "Native"
  },
  {
    serialNo: 88,
    scientificName: "Filicium decipiens (Wight & Arn.) Thwaites",
    commonName: "Japanese Fern Tree",
    kannadaName: "Kattari Mara",
    family: "Sapindaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 16,
    typicalCanopySpreadM: 14,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Tailorbirds", "Flowerpeckers", "Ants"],
    nativeStatus: "Native"
  },
  {
    serialNo: 89,
    scientificName: "Flueggea leucopyrus Willd.",
    commonName: "Indian Bushwillow",
    family: "Phyllanthaceae",
    canopyType: "Deciduous",
    typicalHeightM: 6,
    typicalCanopySpreadM: 5,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Prinias", "Silverline Butterflies"],
    nativeStatus: "Native"
  },
  {
    serialNo: 90,
    scientificName: "Garcinia livingstonei T.Anderson",
    commonName: "African Mangosteen / Imbe",
    family: "Clusiaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 12,
    typicalCanopySpreadM: 10,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Civets", "Fruit Bats", "Tree Squirrels"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 91,
    scientificName: "Gliricidia sepium (Jacq.) Kunth",
    commonName: "Quickstick / Mexican Lilac",
    kannadaName: "Gobbarada Mara",
    family: "Fabaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 10,
    typicalCanopySpreadM: 9,
    ecologicalRole: "Soil & Nitrogen Fixer",
    faunaAffinity: ["Honeybees", "Carpenter Bees", "Sunbirds"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 92,
    scientificName: "Grevillea robusta A. Cunn ex R. Br.",
    commonName: "Silver Oak",
    kannadaName: "Silver Mara",
    family: "Proteaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 26,
    typicalCanopySpreadM: 14,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Sunbirds", "Parakeets", "Arboreal Bats", "Lorises"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 93,
    scientificName: "Guazuma ulmifolia Lam",
    commonName: "West Indian Elm / Bastard Cedar",
    kannadaName: "Rudrakshi Mara",
    family: "Malvaceae",
    canopyType: "Deciduous",
    typicalHeightM: 16,
    typicalCanopySpreadM: 14,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Deer", "Squirrels", "Bulbuls"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 94,
    scientificName: "Handroanthus chrysotrichus (Mart. ex DC.) Mattos",
    commonName: "Golden Trumpet Tree",
    family: "Bignoniaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 12,
    typicalCanopySpreadM: 11,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Purple Sunbird", "Native Bees", "Hummingbird Moths"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 95,
    scientificName: "Handroanthus impetiginosus (Mart. ex DC.) Mattos",
    commonName: "Pink Lapacho / Pink Trumpet Tree",
    family: "Bignoniaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 15,
    typicalCanopySpreadM: 13,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Sunbirds", "Honeybees", "Butterflies"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 96,
    scientificName: "Holoptelea integrifolia (Roxb.) Planch.",
    commonName: "Indian Elm / Kanju",
    kannadaName: "Thapasi Mara",
    family: "Ulmaceae",
    canopyType: "Deciduous",
    typicalHeightM: 24,
    typicalCanopySpreadM: 18,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Grey Slender Loris", "Tree Frogs", "Hornbills"],
    nativeStatus: "Native"
  },
  {
    serialNo: 97,
    scientificName: "Jacaranda mimosifolia D. Don.",
    commonName: "Jacaranda / Blue Mist Tree",
    family: "Bignoniaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 16,
    typicalCanopySpreadM: 15,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Honeybees", "Sunbirds", "Three-striped Palm Squirrel"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 98,
    scientificName: "Khaya grandifoliola C. DC.",
    commonName: "Broadleaf Mahogany",
    family: "Meliaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 30,
    typicalCanopySpreadM: 22,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Grey Slender Loris", "Giant Squirrel", "Raptors"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 99,
    scientificName: "Kigelia pinnata (Lam.) Benth.",
    commonName: "Sausage Tree",
    kannadaName: "Aane Mara",
    family: "Bignoniaceae",
    canopyType: "Deciduous",
    typicalHeightM: 18,
    typicalCanopySpreadM: 16,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Fruit Bats", "Nocturnal Hawk Moths", "Babblers"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 100,
    scientificName: "Lagerstroemia duperreana Pierre. ex Gagnep",
    commonName: "Cambodian Crape Myrtle",
    family: "Lythraceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 14,
    typicalCanopySpreadM: 12,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Bees", "Butterflies", "Sunbirds"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 101,
    scientificName: "Lagerstroemia indica L.",
    commonName: "Crape Myrtle",
    family: "Lythraceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 7,
    typicalCanopySpreadM: 6,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Honeybees", "Leaf Beetles", "Tailorbirds"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 102,
    scientificName: "Lagerstroemia microcarpa Wight",
    commonName: "Ben Teak / Nana",
    kannadaName: "Nandi Mara",
    family: "Lythraceae",
    canopyType: "Deciduous",
    typicalHeightM: 26,
    typicalCanopySpreadM: 18,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Grey Slender Loris", "Woodpeckers", "Civets"],
    nativeStatus: "Native"
  },
  {
    serialNo: 103,
    scientificName: "Lagerstroemia speciosa (L.) Pers.",
    commonName: "Queen's Flower / Pride of India",
    kannadaName: "Challa Mara",
    family: "Lythraceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 20,
    typicalCanopySpreadM: 18,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Purple Sunbird", "Carpenter Bees", "Barbets", "Tree Pipits"],
    nativeStatus: "Native"
  },
  {
    serialNo: 104,
    scientificName: "Leucaena leucocephala (Lam.) de Wit",
    commonName: "Subabul / River Tamarind",
    family: "Fabaceae",
    canopyType: "Deciduous",
    typicalHeightM: 12,
    typicalCanopySpreadM: 8,
    ecologicalRole: "Soil & Nitrogen Fixer",
    faunaAffinity: ["Passerine Birds", "Herbivorous Insects"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 105,
    scientificName: "Libidibia ferrea (Mart. ex Tul.) L.P.Queiroz",
    commonName: "Brazilian Ironwood / Leopard Tree",
    family: "Fabaceae",
    canopyType: "Deciduous",
    typicalHeightM: 18,
    typicalCanopySpreadM: 15,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Sunbirds", "Owlets", "Bees"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 106,
    scientificName: "Limonia acidissima L.",
    commonName: "Wood Apple / Elephant Apple",
    kannadaName: "Belada Mara",
    family: "Rutaceae",
    canopyType: "Deciduous",
    typicalHeightM: 12,
    typicalCanopySpreadM: 10,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Civets", "Bonnet Macaques", "Parakeets"],
    nativeStatus: "Native"
  },
  {
    serialNo: 107,
    scientificName: "Litchi chinensis Sonn.",
    commonName: "Lychee Tree",
    family: "Sapindaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 15,
    typicalCanopySpreadM: 14,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Fruit Bats", "Indian Giant Squirrel", "Bulbuls"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 108,
    scientificName: "Livistona chinensis (Jacq.) R.Br. ex Mart",
    commonName: "Chinese Fan Palm",
    family: "Arecaceae",
    canopyType: "Palm / Conifer",
    typicalHeightM: 14,
    typicalCanopySpreadM: 6,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Palm Swifts", "Spotted Owlets", "Bats"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 109,
    scientificName: "Macadamia integrifolia Maiden & Betche",
    commonName: "Queensland Macadamia Nut",
    family: "Proteaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 14,
    typicalCanopySpreadM: 11,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Parakeets", "Squirrels", "Honeybees"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 110,
    scientificName: "Madhuca longifolia (L.) J.F.Macbr.",
    commonName: "Mahua / Indian Butter Tree",
    kannadaName: "Ippe Mara",
    family: "Sapotaceae",
    canopyType: "Deciduous",
    typicalHeightM: 20,
    typicalCanopySpreadM: 20,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Grey Slender Loris", "Fruit Bats", "Langurs", "Civets", "Over 20 bird species"],
    nativeStatus: "Native"
  },
  {
    serialNo: 111,
    scientificName: "Magnolia champaca (L.) Baill. ex Pierre",
    commonName: "Golden Champa / Joy Perfume Tree",
    kannadaName: "Sampige Mara",
    family: "Magnoliaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 24,
    typicalCanopySpreadM: 17,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Primitive Beetles", "Honeybees", "White-eyes", "Grey Slender Loris"],
    nativeStatus: "Native"
  },
  {
    serialNo: 112,
    scientificName: "Magnolia grandiflora L.",
    commonName: "Southern Magnolia / Bull Bay",
    family: "Magnoliaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 20,
    typicalCanopySpreadM: 16,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Beetles", "Sunbirds", "Canopy Geckoes"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 113,
    scientificName: "Mallotus philippensis (Lam.) Muell.Arg.",
    commonName: "Kamala Tree / Red Dye Tree",
    kannadaName: "Kunkuma Mara",
    family: "Euphorbiaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 12,
    typicalCanopySpreadM: 10,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Drongos", "White-eyes", "Bark Spiders"],
    nativeStatus: "Native"
  },
  {
    serialNo: 114,
    scientificName: "Mammea suriga (Buch.-Ham. ex Roxb.) Kosterm.",
    commonName: "Surangi",
    kannadaName: "Suragi",
    family: "Calophyllaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 18,
    typicalCanopySpreadM: 14,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Wild Bees", "Moths", "Bulbuls"],
    nativeStatus: "Native"
  },
  {
    serialNo: 115,
    scientificName: "Mangifera indica L.",
    commonName: "Mango Tree",
    kannadaName: "Mavina Mara",
    family: "Anacardiaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 25,
    typicalCanopySpreadM: 25,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Grey Slender Loris", "Indian Giant Squirrel", "Koels", "Fruit Bats", "Barbets"],
    nativeStatus: "Native"
  },
  {
    serialNo: 116,
    scientificName: "Manihot carthagenensis (Jacq.) Müll.Arg.",
    commonName: "Cassava Tree",
    family: "Euphorbiaceae",
    canopyType: "Deciduous",
    typicalHeightM: 8,
    typicalCanopySpreadM: 7,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Grasshoppers", "Small Birds"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 117,
    scientificName: "Manilkara zapota (L.) P.Royen",
    commonName: "Sapodilla / Chikoo",
    kannadaName: "Sapota",
    family: "Sapotaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 16,
    typicalCanopySpreadM: 14,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Fruit Bats", "Palm Civets", "Lorises"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 118,
    scientificName: "Markhamia lutea (Benth.) K.Schum.",
    commonName: "Yellow Bells Markhamia",
    family: "Bignoniaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 15,
    typicalCanopySpreadM: 12,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Sunbirds", "Honeybees", "Tailorbirds"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 119,
    scientificName: "Melia azedarach L.",
    commonName: "Chinaberry / Persian Lilac",
    kannadaName: "Thure Bavu",
    family: "Meliaceae",
    canopyType: "Deciduous",
    typicalHeightM: 15,
    typicalCanopySpreadM: 12,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Asian Koel", "Bulbuls", "Carpenter Bees"],
    nativeStatus: "Native"
  },
  {
    serialNo: 120,
    scientificName: "Melia dubia Cav.",
    commonName: "Malabar Neem",
    kannadaName: "Hebbevu",
    family: "Meliaceae",
    canopyType: "Deciduous",
    typicalHeightM: 26,
    typicalCanopySpreadM: 18,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Grey Slender Loris", "Barbets", "Owls"],
    nativeStatus: "Native"
  },
  {
    serialNo: 121,
    scientificName: "Millettia peguensis Ali.",
    commonName: "Moulmein Rosewood",
    family: "Fabaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 14,
    typicalCanopySpreadM: 13,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Sunbirds", "Wild Pollinators"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 122,
    scientificName: "Millettia pinnata (L.) Panigrahi",
    commonName: "Pongam Tree / Indian Beech",
    kannadaName: "Honge Mara",
    family: "Fabaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 18,
    typicalCanopySpreadM: 18,
    ecologicalRole: "Soil & Nitrogen Fixer",
    faunaAffinity: ["Common Banded Peacock", "Sunbirds", "Grey Slender Loris"],
    nativeStatus: "Native"
  },
  {
    serialNo: 123,
    scientificName: "Millingtonia hortensis L.f.",
    commonName: "Indian Cork Tree / Tree Jasmine",
    kannadaName: "Akasha Mallige",
    family: "Bignoniaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 25,
    typicalCanopySpreadM: 14,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Nocturnal Hawk Moths", "Honeybees", "White-eyes"],
    nativeStatus: "Native"
  },
  {
    serialNo: 124,
    scientificName: "Mimusops elengi L.",
    commonName: "Spanish Cherry / Bakul",
    kannadaName: "Ranjalu / Bakula",
    family: "Sapotaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 18,
    typicalCanopySpreadM: 16,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Grey Slender Loris", "Bulbuls", "Barbets", "Flying Foxes"],
    nativeStatus: "Native"
  },
  {
    serialNo: 125,
    scientificName: "Morus nigra L.",
    commonName: "Black Mulberry",
    family: "Moraceae",
    canopyType: "Deciduous",
    typicalHeightM: 12,
    typicalCanopySpreadM: 11,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Over 25 Garden Birds", "Palm Civets", "Lorises"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 126,
    scientificName: "Muntingia calabura L.",
    commonName: "Jamaica Cherry / Singapore Cherry",
    kannadaName: "Gasagase Mara",
    family: "Muntingiaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 10,
    typicalCanopySpreadM: 10,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Pale-billed Flowerpecker", "Fruit Bats", "Three-striped Palm Squirrel"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 127,
    scientificName: "Murraya paniculata (L.) Jack..",
    commonName: "Orange Jessamine / Kamini",
    kannadaName: "Kaadu Karivepu",
    family: "Rutaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 8,
    typicalCanopySpreadM: 6,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Lime Butterfly", "Sunbirds", "Honeybees"],
    nativeStatus: "Native"
  },
  {
    serialNo: 128,
    scientificName: "Neolamarckia cadamba (Roxb.) Bosser",
    commonName: "Kadamba / Burflower Tree",
    kannadaName: "Kadamba Mara",
    family: "Rubiaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 26,
    typicalCanopySpreadM: 20,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Hornbills", "Grey Slender Loris", "Fruit Bats", "Civets"],
    nativeStatus: "Native"
  },
  {
    serialNo: 129,
    scientificName: "Pachira aquatica Aubl.",
    commonName: "Malabar Chestnut / Money Tree",
    family: "Malvaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 16,
    typicalCanopySpreadM: 12,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Fruit Bats", "Arboreal Geckoes"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 130,
    scientificName: "Parkia biglandulosa Wight & Arn.",
    commonName: "Badminton Ball Tree",
    kannadaName: "Chendu Hoovina Mara",
    family: "Fabaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 24,
    typicalCanopySpreadM: 22,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Fruit Bats", "Grey Slender Loris", "Honeybees", "Squirrels"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 131,
    scientificName: "Peltophorum pterocarpum (DC.) Backer ex K.Heyne",
    commonName: "Copperpod / Yellow Flame Tree",
    kannadaName: "Haladi Gulmohar",
    family: "Fabaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 22,
    typicalCanopySpreadM: 22,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Honeybees", "Grey Slender Loris", "Purple Sunbird", "Barbets"],
    nativeStatus: "Native"
  },
  {
    serialNo: 132,
    scientificName: "Persea americana Mill.",
    commonName: "Avocado / Butter Fruit",
    family: "Lauraceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 15,
    typicalCanopySpreadM: 12,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Civets", "Arboreal Rodents"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 133,
    scientificName: "Persea macrantha (Nees) Kosterm.",
    commonName: "Large-flowered Bay",
    kannadaName: "Gulmavu",
    family: "Lauraceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 20,
    typicalCanopySpreadM: 16,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Hornbills", "Grey Slender Loris", "Tree Frogs"],
    nativeStatus: "Native"
  },
  {
    serialNo: 134,
    scientificName: "Phoenix sylvestris (L.) Roxb.",
    commonName: "Wild Date Palm / Silver Date Palm",
    kannadaName: "Eechala Mara",
    family: "Arecaceae",
    canopyType: "Palm / Conifer",
    typicalHeightM: 14,
    typicalCanopySpreadM: 6,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Palm Civets", "Lorises", "Bulbuls", "Fruit Bats"],
    nativeStatus: "Native"
  },
  {
    serialNo: 135,
    scientificName: "Phyllanthus acidus (L.) Skeels",
    commonName: "Star Gooseberry",
    kannadaName: "Kirunelli",
    family: "Phyllanthaceae",
    canopyType: "Deciduous",
    typicalHeightM: 9,
    typicalCanopySpreadM: 7,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Parakeets", "Squirrels", "Bulbuls"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 136,
    scientificName: "Phyllanthus emblica L.",
    commonName: "Indian Gooseberry / Amla",
    kannadaName: "Nelli Mara",
    family: "Phyllanthaceae",
    canopyType: "Deciduous",
    typicalHeightM: 12,
    typicalCanopySpreadM: 10,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Deer", "Monkeys", "Parakeets", "Honeybees"],
    nativeStatus: "Native"
  },
  {
    serialNo: 137,
    scientificName: "Pimenta dioica (L.) Merr.",
    commonName: "Allspice / Pimento",
    family: "Myrtaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 13,
    typicalCanopySpreadM: 10,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Insectivorous Birds", "Bark Geckos"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 138,
    scientificName: "Pithecellobium dulce (Roxb.) Benth.",
    commonName: "Manila Tamarind / Madras Thorn",
    kannadaName: "Seeme Hunase",
    family: "Fabaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 14,
    typicalCanopySpreadM: 14,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Parakeets", "Babblers", "Squirrels", "Lorises"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 139,
    scientificName: "Plumeria alba L.",
    commonName: "White Frangipani",
    family: "Apocynaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 8,
    typicalCanopySpreadM: 7,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Sphinx Moths", "Tree Frogs"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 140,
    scientificName: "Plumeria obtusa L.",
    commonName: "Singapore Graveyard Flower",
    family: "Apocynaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 7,
    typicalCanopySpreadM: 6,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Moths", "Butterflies"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 141,
    scientificName: "Plumeria rubra L.",
    commonName: "Red Frangipani / Temple Tree",
    kannadaName: "Devakanagalu",
    family: "Apocynaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 9,
    typicalCanopySpreadM: 8,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Hawkmoths", "Sunbirds"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 142,
    scientificName: "Monoon longifolium (Sonn.) B. Xue & R.M.K. Saunders",
    commonName: "Mast Tree / False Ashoka",
    kannadaName: "Ubbina Mara",
    family: "Annonaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 20,
    typicalCanopySpreadM: 6,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Fruit Bats", "Asian Koel", "Spotted Owlets"],
    nativeStatus: "Native"
  },
  {
    serialNo: 143,
    scientificName: "Pterocarpus marsupium Roxb.",
    commonName: "Indian Kino Tree / Malabar Kino",
    kannadaName: "Honne",
    family: "Fabaceae",
    canopyType: "Deciduous",
    typicalHeightM: 25,
    typicalCanopySpreadM: 19,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Grey Slender Loris", "Honeybees", "Woodpeckers"],
    nativeStatus: "Native",
    conservationNote: "Vulnerable red-listed timber"
  },
  {
    serialNo: 144,
    scientificName: "Pterocymbium tinctorium (Blanco) Merr.",
    commonName: "Amberoi",
    family: "Malvaceae",
    canopyType: "Deciduous",
    typicalHeightM: 26,
    typicalCanopySpreadM: 17,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Raptors", "Canopy Doves"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 145,
    scientificName: "Pterospermum acerifolium (L.) Willd.",
    commonName: "Dinnerplate Tree / Kanak Champa",
    kannadaName: "Kanakachampa",
    family: "Malvaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 20,
    typicalCanopySpreadM: 18,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Giant Wood Spiders", "Flying Foxes", "Owls"],
    nativeStatus: "Native"
  },
  {
    serialNo: 146,
    scientificName: "Pterygota alata (Roxb.) R. Br.",
    commonName: "Buddha Coconut",
    family: "Malvaceae",
    canopyType: "Deciduous",
    typicalHeightM: 28,
    typicalCanopySpreadM: 20,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Parakeets", "Grey Slender Loris", "Owlets"],
    nativeStatus: "Native"
  },
  {
    serialNo: 147,
    scientificName: "Putranjiva roxburghii Wall.",
    commonName: "Child-life Tree / Lucky Bean Tree",
    kannadaName: "Putranjiva",
    family: "Putranjivaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 18,
    typicalCanopySpreadM: 15,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Tailorbirds", "Bark Geckos", "White-eyes"],
    nativeStatus: "Native"
  },
  {
    serialNo: 148,
    scientificName: "Reutealis trisperma (Blanco) Airy Shaw",
    commonName: "Philippine Tung Tree / Bagilumbang",
    family: "Euphorbiaceae",
    canopyType: "Deciduous",
    typicalHeightM: 16,
    typicalCanopySpreadM: 13,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Weevils", "Canopy Mantids"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 149,
    scientificName: "Roseodendron donnell-smithii (Rose) Miranda",
    commonName: "Primavera / Gold Tree",
    family: "Bignoniaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 24,
    typicalCanopySpreadM: 16,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Sunbirds", "Honeybees", "Butterflies"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 150,
    scientificName: "Roystonea regia (Kunth.) O.F.Cook",
    commonName: "Royal Palm",
    family: "Arecaceae",
    canopyType: "Palm / Conifer",
    typicalHeightM: 25,
    typicalCanopySpreadM: 7,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Palm Swifts", "Spotted Owlets", "Bats"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 151,
    scientificName: "Samanea saman (Jacq.) Merr.",
    commonName: "Rain Tree / Monkey Pod",
    kannadaName: "Male Mara",
    family: "Fabaceae",
    canopyType: "Deciduous",
    typicalHeightM: 28,
    typicalCanopySpreadM: 35,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Grey Slender Loris", "Indian Giant Squirrel", "Owls", "Epiphytic Orchids", "Over 35 bird species"],
    nativeStatus: "Introduced / Naturalized",
    conservationNote: "Critical arterial canopy bridge in Cubbon Park"
  },
  {
    serialNo: 152,
    scientificName: "Santalum album L.",
    commonName: "Indian Sandalwood",
    kannadaName: "Gandhada Mara",
    family: "Santalaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 14,
    typicalCanopySpreadM: 10,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Bulbuls", "Koels", "Root Mycorrhizae", "Grey Slender Loris"],
    nativeStatus: "Native",
    conservationNote: "Vulnerable iconic state tree"
  },
  {
    serialNo: 153,
    scientificName: "Sapindus emarginatus Vahl.",
    commonName: "Soapnut / Reetha",
    kannadaName: "Aritha Mara",
    family: "Sapindaceae",
    canopyType: "Deciduous",
    typicalHeightM: 15,
    typicalCanopySpreadM: 13,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Parakeets", "Honeybees", "Squirrels"],
    nativeStatus: "Native"
  },
  {
    serialNo: 154,
    scientificName: "Sapindus laurifolius Vahl.",
    commonName: "South Indian Soapnut",
    kannadaName: "Kugate Mara",
    family: "Sapindaceae",
    canopyType: "Deciduous",
    typicalHeightM: 16,
    typicalCanopySpreadM: 14,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Bulbuls", "Palm Civets", "Tree Frogs"],
    nativeStatus: "Native"
  },
  {
    serialNo: 155,
    scientificName: "Saraca asoca (Roxb.) W.J.de Wilde",
    commonName: "Sita Ashoka",
    kannadaName: "Ashoka Mara",
    family: "Fabaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 12,
    typicalCanopySpreadM: 11,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Sunbirds", "Honeybees", "Grey Slender Loris"],
    nativeStatus: "Native",
    conservationNote: "Endangered indigenous heritage flora"
  },
  {
    serialNo: 156,
    scientificName: "Schefflera actinophylla (Endl.) Harms",
    commonName: "Umbrella Tree / Octopus Tree",
    family: "Araliaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 12,
    typicalCanopySpreadM: 10,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Lorikeets", "Sunbirds", "Honeybees"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 157,
    scientificName: "Schotia brachypetala Sond.",
    commonName: "Weeping Boer-bean / Fuchsia Tree",
    family: "Fabaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 14,
    typicalCanopySpreadM: 12,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Sunbirds", "Bees", "Monkeys"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 158,
    scientificName: "Senegalia polyacantha (Willd.) Seigler & Ebinger",
    commonName: "White-stemmed Acacia",
    family: "Fabaceae",
    canopyType: "Deciduous",
    typicalHeightM: 18,
    typicalCanopySpreadM: 14,
    ecologicalRole: "Soil & Nitrogen Fixer",
    faunaAffinity: ["Langurs", "Tree Pipits", "Hornets"],
    nativeStatus: "Native"
  },
  {
    serialNo: 159,
    scientificName: "Senna montana (B.Heyne ex Roth) V.Singh",
    commonName: "Mountain Senna",
    family: "Fabaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 8,
    typicalCanopySpreadM: 7,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Yellow Butterflies", "Native Bees"],
    nativeStatus: "Native"
  },
  {
    serialNo: 160,
    scientificName: "Senna siamea (Lam.) H.S.Irwin & Barneby",
    commonName: "Kassod Tree / Siamese Senna",
    kannadaName: "Simethangadi",
    family: "Fabaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 18,
    typicalCanopySpreadM: 16,
    ecologicalRole: "Soil & Nitrogen Fixer",
    faunaAffinity: ["Common Emigrant Butterfly", "Sunbirds", "Squirrels"],
    nativeStatus: "Native"
  },
  {
    serialNo: 161,
    scientificName: "Senna spectabilis (DC.) H.S.Irwin & Barneby",
    commonName: "Golden Wonder Tree",
    family: "Fabaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 14,
    typicalCanopySpreadM: 13,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Butterflies", "Bees"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 162,
    scientificName: "Simarouba glauca DC.",
    commonName: "Paradise Tree / Laxmitaru",
    family: "Simaroubaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 14,
    typicalCanopySpreadM: 11,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Birds", "Bees"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 163,
    scientificName: "Spathodea campanulata P.Beauv.",
    commonName: "African Tulip Tree / Flame of Nandi",
    kannadaName: "Neerukayi Mara",
    family: "Bignoniaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 22,
    typicalCanopySpreadM: 18,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Sunbirds", "Mynas", "Parakeets", "Grey Slender Loris"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 164,
    scientificName: "Stenocarpus sinuatus (Lindl.) Endl.",
    commonName: "Firewheel Tree",
    family: "Proteaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 18,
    typicalCanopySpreadM: 12,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Sunbirds", "Honeyeaters", "Bees"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 165,
    scientificName: "Sterculia balanghas L.",
    commonName: "Balanghas Sterculia",
    family: "Malvaceae",
    canopyType: "Deciduous",
    typicalHeightM: 18,
    typicalCanopySpreadM: 14,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Parakeets", "Squirrels", "Bark Beetles"],
    nativeStatus: "Native"
  },
  {
    serialNo: 166,
    scientificName: "Sterculia foetida L.",
    commonName: "Wild Almond / Java Olive",
    kannadaName: "Bhatala Penari",
    family: "Malvaceae",
    canopyType: "Deciduous",
    typicalHeightM: 26,
    typicalCanopySpreadM: 20,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Blowflies", "Fruit Bats", "Indian Giant Squirrel"],
    nativeStatus: "Native"
  },
  {
    serialNo: 167,
    scientificName: "Stereospermum tetragonum DC.",
    commonName: "Yellow Snake Tree / Padri",
    kannadaName: "Padari Mara",
    family: "Bignoniaceae",
    canopyType: "Deciduous",
    typicalHeightM: 20,
    typicalCanopySpreadM: 15,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Hawk Moths", "Tree Frogs", "White-eyes"],
    nativeStatus: "Native"
  },
  {
    serialNo: 168,
    scientificName: "Swietenia macrophylla King",
    commonName: "Big-leaf Mahogany / Honduran Mahogany",
    family: "Meliaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 32,
    typicalCanopySpreadM: 24,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Grey Slender Loris", "Spotted Owlets", "Giant Flying Squirrel"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 169,
    scientificName: "Swietenia mahagoni (L.) Jacq.",
    commonName: "West Indian Mahogany",
    family: "Meliaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 26,
    typicalCanopySpreadM: 20,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Canopy Birds", "Owlets", "Lorises"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 170,
    scientificName: "Syzygium cuminii (L.) Skeels",
    commonName: "Jamun / Java Plum",
    kannadaName: "Nerale Mara",
    family: "Myrtaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 25,
    typicalCanopySpreadM: 22,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Grey Slender Loris", "Koels", "Civets", "Fruit Bats", "Barbets"],
    nativeStatus: "Native"
  },
  {
    serialNo: 171,
    scientificName: "Tabebuia aurea (Silva Manso) Benth. & Hook.f. ex S.Moore",
    commonName: "Silver Trumpet Tree / Caribbean Trumpet",
    family: "Bignoniaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 10,
    typicalCanopySpreadM: 9,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Sunbirds", "Honeybees", "Butterflies"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 172,
    scientificName: "Tabebuia pallida (Lindley) Miers",
    commonName: "White Cedar / Cuban Pink Trumpet",
    family: "Bignoniaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 14,
    typicalCanopySpreadM: 12,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Sunbirds", "White-eyes", "Bees"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 173,
    scientificName: "Tabebuia rosea (Bertol) DC.",
    commonName: "Pink Poui / Rosy Trumpet Tree",
    kannadaName: "Gulabi Trumpet Mara",
    family: "Bignoniaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 22,
    typicalCanopySpreadM: 19,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Purple Sunbird", "Honeybees", "Three-striped Palm Squirrel", "Bulbuls"],
    nativeStatus: "Introduced / Naturalized",
    conservationNote: "Bangalore's iconic spring cherry blossom equivalent"
  },
  {
    serialNo: 174,
    scientificName: "Tamarindus indica L.",
    commonName: "Tamarind Tree",
    kannadaName: "Hunase Mara",
    family: "Fabaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 24,
    typicalCanopySpreadM: 26,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Grey Slender Loris", "Indian Giant Squirrel", "Parakeets", "Bonnet Macaques"],
    nativeStatus: "Native"
  },
  {
    serialNo: 175,
    scientificName: "Tecoma stans s (L.) Juss. ex Kunth",
    commonName: "Yellow Elder / Yellow Bells",
    family: "Bignoniaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 8,
    typicalCanopySpreadM: 7,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Sunbirds", "Bees", "Skipper Butterflies"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 176,
    scientificName: "Tectona grandis L.f.",
    commonName: "Teak Tree",
    kannadaName: "Saguvani Mara",
    family: "Lamiaceae",
    canopyType: "Deciduous",
    typicalHeightM: 28,
    typicalCanopySpreadM: 18,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Teak Defoliator Moths", "Woodpeckers", "Spotted Owlets"],
    nativeStatus: "Native"
  },
  {
    serialNo: 177,
    scientificName: "Terminalia arjuna (Roxb. ex DC.) Wight & Arn.",
    commonName: "Arjun Tree",
    kannadaName: "Maddi Mara",
    family: "Combretaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 28,
    typicalCanopySpreadM: 26,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Grey Slender Loris", "Giant Squirrel", "White-rumped Vultures", "Fruit Bats"],
    nativeStatus: "Native"
  },
  {
    serialNo: 178,
    scientificName: "Terminalia bellirica (Gaertn.) Roxb.",
    commonName: "Bahera / Belleric Myrobalan",
    kannadaName: "Tare Mara",
    family: "Combretaceae",
    canopyType: "Deciduous",
    typicalHeightM: 26,
    typicalCanopySpreadM: 22,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Grey Slender Loris", "Langurs", "Flying Foxes", "Bark Creepers"],
    nativeStatus: "Native"
  },
  {
    serialNo: 179,
    scientificName: "Terminalia catappa L.",
    commonName: "Indian Almond / Sea Almond",
    kannadaName: "Badami Mara",
    family: "Combretaceae",
    canopyType: "Deciduous",
    typicalHeightM: 22,
    typicalCanopySpreadM: 20,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Fruit Bats", "Parakeets", "Squirrels", "Civets"],
    nativeStatus: "Native"
  },
  {
    serialNo: 180,
    scientificName: "Terminalia mantaly H.Perrier",
    commonName: "Madagascar Almond / Umbrella Tree",
    family: "Combretaceae",
    canopyType: "Deciduous",
    typicalHeightM: 18,
    typicalCanopySpreadM: 16,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Weaver Ants", "Drongos", "White-eyes"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 181,
    scientificName: "Thespesia populnea (L.) Sol. ex Correa",
    commonName: "Portia Tree / Indian Tulip Tree",
    kannadaName: "Huvarasi",
    family: "Malvaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 14,
    typicalCanopySpreadM: 12,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Cotton Stainer Bugs", "Sunbirds"],
    nativeStatus: "Native"
  },
  {
    serialNo: 182,
    scientificName: "Toona ciliata M. Roem.",
    commonName: "Red Cedar / Indian Toon",
    kannadaName: "Gandu Garige",
    family: "Meliaceae",
    canopyType: "Deciduous",
    typicalHeightM: 28,
    typicalCanopySpreadM: 19,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Grey Slender Loris", "Barbets", "Woodpeckers"],
    nativeStatus: "Native"
  },
  {
    serialNo: 183,
    scientificName: "Triplaris weigeltiana (Rchb.) Kuntze",
    commonName: "Ant Tree",
    family: "Polygonaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 20,
    typicalCanopySpreadM: 13,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Symbiotic Pseudomyrmex Ants", "Woodpeckers"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 184,
    scientificName: "Vachellia leucophloea (Roxb.) Maslin, Seigler & Ebinger",
    commonName: "White Bark Acacia / Distiller's Acacia",
    kannadaName: "Nalavalu",
    family: "Fabaceae",
    canopyType: "Deciduous",
    typicalHeightM: 16,
    typicalCanopySpreadM: 14,
    ecologicalRole: "Soil & Nitrogen Fixer",
    faunaAffinity: ["Baya Weavers", "Sunbirds", "Honeybees"],
    nativeStatus: "Native"
  },
  {
    serialNo: 185,
    scientificName: "Vitex altissima L.f.",
    commonName: "Peacock Chaste Tree / Tall Vitex",
    kannadaName: "Navaladi",
    family: "Lamiaceae",
    canopyType: "Deciduous",
    typicalHeightM: 24,
    typicalCanopySpreadM: 18,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Grey Slender Loris", "Barbets", "Wild Bees"],
    nativeStatus: "Native"
  },
  {
    serialNo: 186,
    scientificName: "Vitex negundo L.",
    commonName: "Five-leaved Chaste Tree / Nirgundi",
    kannadaName: "Lakkagida",
    family: "Lamiaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 6,
    typicalCanopySpreadM: 5,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Tiger Butterflies", "Honeybees", "Spiders"],
    nativeStatus: "Native"
  },
  {
    serialNo: 187,
    scientificName: "Wodyetia bifurcata A.K.Irvine",
    commonName: "Foxtail Palm",
    family: "Arecaceae",
    canopyType: "Palm / Conifer",
    typicalHeightM: 15,
    typicalCanopySpreadM: 6,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Swifts", "Lorises", "Bats"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 188,
    scientificName: "Ziziphus mauritiana Lam.",
    commonName: "Indian Jujube / Ber",
    kannadaName: "Yelachi Mara",
    family: "Rhamnaceae",
    canopyType: "Deciduous",
    typicalHeightM: 12,
    typicalCanopySpreadM: 11,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Civets", "Grey Slender Loris", "Bulbuls", "Monkeys"],
    nativeStatus: "Native"
  },
  {
    serialNo: 189,
    scientificName: "Parmentiera cereifera Seem.",
    commonName: "Candle Tree",
    family: "Bignoniaceae",
    canopyType: "Deciduous",
    typicalHeightM: 8,
    typicalCanopySpreadM: 7,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Nocturnal Bats", "Arboreal Geckoes"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 190,
    scientificName: "Clerodendrum pleiosciadium Gürke",
    commonName: "Umbrella Clerodendrum",
    family: "Lamiaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 7,
    typicalCanopySpreadM: 6,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Hawkmoths", "Sunbirds", "Butterflies"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 191,
    scientificName: "Ceodes grandis (R.Br.) D.Q.Lu",
    commonName: "Bird-lime Tree / Great Pisonia",
    family: "Nyctaginaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 18,
    typicalCanopySpreadM: 15,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Roosting Seabirds / Herons", "Tree Geckos"],
    nativeStatus: "Native"
  },
  {
    serialNo: 192,
    scientificName: "Cananga odorata (Lam.) Hook.f. & Thomson",
    commonName: "Ylang-Ylang / Cananga",
    family: "Annonaceae",
    canopyType: "Flowering Canopy",
    typicalHeightM: 20,
    typicalCanopySpreadM: 14,
    ecologicalRole: "Nectar / Pollinator Anchor",
    faunaAffinity: ["Night Hawkmoths", "Fruit Bats", "Sunbirds"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 193,
    scientificName: "Spondias L.",
    commonName: "Hog Plum / Ambarella",
    kannadaName: "Amate Mara",
    family: "Anacardiaceae",
    canopyType: "Deciduous",
    typicalHeightM: 22,
    typicalCanopySpreadM: 18,
    ecologicalRole: "Keystone Food Source",
    faunaAffinity: ["Grey Slender Loris", "Civets", "Langurs", "Fruit Bats"],
    nativeStatus: "Native"
  },
  {
    serialNo: 194,
    scientificName: "Diospyros montana Roxb. L.",
    commonName: "Mountain Persimmon / Bombay Ebony",
    kannadaName: "Jagala Ganti",
    family: "Ebenaceae",
    canopyType: "Deciduous",
    typicalHeightM: 14,
    typicalCanopySpreadM: 11,
    ecologicalRole: "Medicinal & Microclimate",
    faunaAffinity: ["Bulbuls", "Koels", "Arboreal Lizards"],
    nativeStatus: "Native"
  },
  {
    serialNo: 195,
    scientificName: "Conocarpus lancifolius Engl.",
    commonName: "Damask / Buttonwood",
    family: "Combretaceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 15,
    typicalCanopySpreadM: 12,
    ecologicalRole: "Soil & Nitrogen Fixer",
    faunaAffinity: ["Tailorbirds", "Bark Foragers", "Ants"],
    nativeStatus: "Introduced / Naturalized"
  },
  {
    serialNo: 196,
    scientificName: "Ficus altissima Blume.",
    commonName: "Council Tree / False Banyan",
    kannadaName: "Dodda Goli",
    family: "Moraceae",
    canopyType: "Broadleaf Evergreen",
    typicalHeightM: 28,
    typicalCanopySpreadM: 32,
    ecologicalRole: "Mother Tree / Continuous Canopy",
    faunaAffinity: ["Grey Slender Loris", "Indian Giant Squirrel", "Hornbills", "Over 35 bird species"],
    nativeStatus: "Native"
  }
];

export const CUBBON_ZONES = [
  {
    id: "zone-bandstand",
    name: "Bandstand & Queen's Promenade",
    description: "Centuries-old promenade hosting heritage Ficus, Rain Trees, and Mahua trees. Primary artery for arboreal mammals.",
    center: { lat: 12.9762, lng: 77.5929 },
    color: "#606C38",
  },
  {
    id: "zone-bamboo",
    name: "Bamboo Grove & Lotus Pond",
    description: "Moist microclimate sanctuary vital for amphibians, insectivorous birds, and roosting spotted owlets.",
    center: { lat: 12.9745, lng: 77.5912 },
    color: "#283618",
  },
  {
    id: "zone-bal-bhavan",
    name: "Bal Bhavan & Children's Canopy",
    description: "Lush flowering canopy with Gulmohars, Tabebuias, and Jacarandas supporting high pollinator density.",
    center: { lat: 12.9780, lng: 77.5955 },
    color: "#DDA15E",
  },
  {
    id: "zone-high-court",
    name: "Attara Kacheri & Central Ridge",
    description: "Dense avenue of Swietenia, Samanea, and Cassia lining heritage architecture.",
    center: { lat: 12.9788, lng: 77.5915 },
    color: "#BC6C25",
  },
  {
    id: "zone-library",
    name: "State Central Library Grounds",
    description: "Heritage red terracotta library framed by 100+ year old Araucarias, Bipinnate trees, and Banyan groves.",
    center: { lat: 12.9752, lng: 77.5940 },
    color: "#606C38",
  }
];
