import { Tree, Species, Corridor, Project } from '@/types';

// Cubbon Park, Bengaluru coordinates: ~12.9762° N, 77.5929° E
const CUBBON_PARK_CENTER = { lat: 12.9762, lng: 77.5929 };

export const demoProject: Project = {
  id: 1,
  userId: 1,
  name: 'Cubbon Park Ecological Assessment',
  location: 'Cubbon Park, Bengaluru',
  description: 'Comprehensive ecological connectivity analysis of Cubbon Park urban forest',
  bounds: {
    type: 'Polygon',
    coordinates: [[
      [77.5900, 12.9800],
      [77.5960, 12.9800],
      [77.5960, 12.9720],
      [77.5900, 12.9720],
      [77.5900, 12.9800],
    ]],
  },
  baselineConnectivity: 82,
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const demoSpecies: Species[] = [
  {
    id: 1,
    name: 'Grey Slender Loris',
    commonName: 'Grey Slender Loris',
    scientificName: 'Loris lydekkerianus',
    habitatType: 'Canopy',
    canopyDependency: 'high',
    sensitivity: 'high',
    description: 'A nocturnal primate that depends on continuous canopy cover for movement and survival. Highly sensitive to habitat fragmentation.',
    imageUrl: null,
  },
  {
    id: 2,
    name: 'Indian Giant Squirrel',
    commonName: 'Indian Giant Squirrel',
    scientificName: 'Ratufa indica',
    habitatType: 'Canopy',
    canopyDependency: 'high',
    sensitivity: 'medium',
    description: 'Large tree squirrel that requires connected canopy pathways for foraging and territory movement.',
    imageUrl: null,
  },
  {
    id: 3,
    name: 'Common Tailorbird',
    commonName: 'Common Tailorbird',
    scientificName: 'Orthotomus sutorius',
    habitatType: 'Canopy',
    canopyDependency: 'medium',
    sensitivity: 'low',
    description: 'Small bird that nests in trees and benefits from dense vegetation cover.',
    imageUrl: null,
  },
  {
    id: 4,
    name: 'Purple Sunbird',
    commonName: 'Purple Sunbird',
    scientificName: 'Cinnyris asiaticus',
    habitatType: 'Canopy',
    canopyDependency: 'medium',
    sensitivity: 'low',
    description: 'Nectarivorous bird that pollinates flowering trees and shrubs.',
    imageUrl: null,
  },
];

export const demoTrees: Tree[] = [
  // Critical Tree #21 - The hero of our story
  {
    id: 21,
    projectId: 1,
    treeNumber: 'TREE-021',
    species: 'Rain Tree',
    commonName: 'Rain Tree',
    age: 74,
    canopyRadius: 18.4,
    height: 22.5,
    ecologicalValue: 'critical',
    connectivityContribution: 12,
    lat: 12.9762,
    lng: 77.5929,
    status: 'active',
    isCriticalNode: true,
    metadata: {
      healthStatus: 'excellent',
      lastInspection: '2024-01-15',
    },
  },
  // Supporting trees in the network
  {
    id: 1,
    projectId: 1,
    treeNumber: 'TREE-001',
    species: 'Banyan Tree',
    commonName: 'Banyan',
    age: 120,
    canopyRadius: 25.0,
    height: 28.0,
    ecologicalValue: 'critical',
    connectivityContribution: 15,
    lat: 12.9770,
    lng: 77.5935,
    status: 'active',
    isCriticalNode: true,
    metadata: {},
  },
  {
    id: 2,
    projectId: 1,
    treeNumber: 'TREE-002',
    species: 'Peepal Tree',
    commonName: 'Sacred Fig',
    age: 85,
    canopyRadius: 20.0,
    height: 25.0,
    ecologicalValue: 'high',
    connectivityContribution: 10,
    lat: 12.9755,
    lng: 77.5925,
    status: 'active',
    isCriticalNode: false,
    metadata: {},
  },
  {
    id: 3,
    projectId: 1,
    treeNumber: 'TREE-003',
    species: 'Neem Tree',
    commonName: 'Neem',
    age: 65,
    canopyRadius: 15.0,
    height: 18.0,
    ecologicalValue: 'high',
    connectivityContribution: 8,
    lat: 12.9765,
    lng: 77.5920,
    status: 'active',
    isCriticalNode: false,
    metadata: {},
  },
  {
    id: 4,
    projectId: 1,
    treeNumber: 'TREE-004',
    species: 'Tamarind Tree',
    commonName: 'Tamarind',
    age: 90,
    canopyRadius: 16.5,
    height: 20.0,
    ecologicalValue: 'high',
    connectivityContribution: 9,
    lat: 12.9758,
    lng: 77.5933,
    status: 'active',
    isCriticalNode: true,
    metadata: {},
  },
  {
    id: 5,
    projectId: 1,
    treeNumber: 'TREE-005',
    species: 'Ashoka Tree',
    commonName: 'Ashoka',
    age: 45,
    canopyRadius: 12.0,
    height: 15.0,
    ecologicalValue: 'medium',
    connectivityContribution: 5,
    lat: 12.9768,
    lng: 77.5928,
    status: 'active',
    isCriticalNode: false,
    metadata: {},
  },
  {
    id: 6,
    projectId: 1,
    treeNumber: 'TREE-006',
    species: 'Gulmohar Tree',
    commonName: 'Flame Tree',
    age: 55,
    canopyRadius: 14.0,
    height: 16.5,
    ecologicalValue: 'medium',
    connectivityContribution: 6,
    lat: 12.9750,
    lng: 77.5930,
    status: 'active',
    isCriticalNode: false,
    metadata: {},
  },
  {
    id: 7,
    projectId: 1,
    treeNumber: 'TREE-007',
    species: 'Mango Tree',
    commonName: 'Mango',
    age: 70,
    canopyRadius: 17.0,
    height: 19.0,
    ecologicalValue: 'high',
    connectivityContribution: 8,
    lat: 12.9773,
    lng: 77.5922,
    status: 'active',
    isCriticalNode: false,
    metadata: {},
  },
  {
    id: 8,
    projectId: 1,
    treeNumber: 'TREE-008',
    species: 'Jackfruit Tree',
    commonName: 'Jackfruit',
    age: 60,
    canopyRadius: 13.5,
    height: 17.0,
    ecologicalValue: 'medium',
    connectivityContribution: 6,
    lat: 12.9760,
    lng: 77.5936,
    status: 'active',
    isCriticalNode: false,
    metadata: {},
  },
  {
    id: 9,
    projectId: 1,
    treeNumber: 'TREE-009',
    species: 'Coconut Palm',
    commonName: 'Coconut',
    age: 40,
    canopyRadius: 8.0,
    height: 18.0,
    ecologicalValue: 'low',
    connectivityContribution: 3,
    lat: 12.9752,
    lng: 77.5927,
    status: 'active',
    isCriticalNode: false,
    metadata: {},
  },
  {
    id: 10,
    projectId: 1,
    treeNumber: 'TREE-010',
    species: 'Jamun Tree',
    commonName: 'Java Plum',
    age: 68,
    canopyRadius: 15.5,
    height: 18.5,
    ecologicalValue: 'high',
    connectivityContribution: 7,
    lat: 12.9766,
    lng: 77.5924,
    status: 'active',
    isCriticalNode: false,
    metadata: {},
  },
  {
    id: 11,
    projectId: 1,
    treeNumber: 'TREE-011',
    species: 'Bamboo',
    commonName: 'Bamboo',
    age: 15,
    canopyRadius: 6.0,
    height: 12.0,
    ecologicalValue: 'medium',
    connectivityContribution: 4,
    lat: 12.9757,
    lng: 77.5931,
    status: 'active',
    isCriticalNode: false,
    metadata: {},
  },
  {
    id: 12,
    projectId: 1,
    treeNumber: 'TREE-012',
    species: 'Ficus Tree',
    commonName: 'Fig',
    age: 95,
    canopyRadius: 22.0,
    height: 26.0,
    ecologicalValue: 'critical',
    connectivityContribution: 13,
    lat: 12.9771,
    lng: 77.5930,
    status: 'active',
    isCriticalNode: true,
    metadata: {},
  },
];

export const demoCorridor: Corridor = {
  id: 1,
  projectId: 1,
  name: 'Grey Slender Loris Primary Corridor',
  speciesId: 1,
  connectivityScore: 82,
  length: 1.7,
  criticalTreeCount: 23,
  threatLevel: 'high',
  potentialFragmentation: 17,
  geometry: {
    type: 'LineString',
    coordinates: [
      [77.5920, 12.9770],
      [77.5929, 12.9762],
      [77.5935, 12.9755],
    ],
  },
  status: 'intact',
};
